package ru.lifegame.backend.config;

import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.ResourceHandlerRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;

/**
 * Configures Spring MVC to serve static assets generated by asset-generator module.
 * Maps /assets/** requests to classpath:/assets/ directory recursively.
 * <p>
 * Files are copied by Maven from backend/target/generated-assets/ to classpath:/assets/
 * preserving directory structure (characters/, locations/, etc.).
 */
@Configuration
public class StaticResourceConfig implements WebMvcConfigurer {

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry
                .addResourceHandler("/assets/**")
                .addResourceLocations("classpath:/assets/")
                .setCachePeriod(3600); // 1 hour cache for static assets
    }
}
