package ru.lifegame.backend.config;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.ResourceHandlerRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;

/**
 * Configures Spring MVC to serve static assets generated by asset-generator module.
 * Maps /assets/** requests to:
 *   1. classpath:/assets/ (embedded in JAR during build)
 *   2. file://{assets.output-dir}/ (filesystem path to generated assets)
 * <p>
 * Files are copied by Maven from backend/target/generated-assets/ to classpath:/assets/
 * preserving directory structure (characters/, locations/, etc.).
 * Filesystem path allows serving assets directly from generator output during development.
 */
@Configuration
public class StaticResourceConfig implements WebMvcConfigurer {

    @Value("${assets.output-dir}")
    private String assetsOutputDir;

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        // Normalize file path (ensure trailing slash)
        String fileLocation = "file:" + assetsOutputDir;
        if (!fileLocation.endsWith("/")) {
            fileLocation += "/";
        }

        registry
                .addResourceHandler("/assets/**")
                .addResourceLocations(
                        "classpath:/assets/",  // JAR-embedded assets
                        fileLocation            // Filesystem assets (dev mode)
                )
                .setCachePeriod(3600); // 1 hour cache for static assets
    }
}
