/**
 * Types for sprite animation system.
 * Maps to sprite-atlas.json v1.1 generated by asset-generator.
 */

/* ──────────────────── sprite-atlas.json schema ──────────────────── */

/** Condition for row selection in grid layouts */
export interface AtlasCondition {
  readonly type: string;   // e.g. "time_of_day"
  readonly value: string;  // e.g. "morning"
}

/** Row definition in a grid animation */
export interface AtlasRowDef {
  readonly rowIndex: number;
  readonly condition: AtlasCondition;
  readonly fps: number;
  readonly loop: boolean;
}

/** Single animation entry in sprite-atlas.json */
export interface AtlasAnimationEntry {
  readonly file: string;
  readonly layout: 'strip' | 'grid';
  readonly columns: number;
  readonly frameWidth: number;
  readonly frameHeight: number;
  // strip fields
  readonly fps?: number;
  readonly loop?: boolean;
  // grid fields
  readonly rows?: readonly AtlasRowDef[];
  readonly defaultRow?: number;
}

/** Root of sprite-atlas.json (v1.1 object format) */
export interface AtlasConfig {
  readonly configVersion: string;
  readonly revision: string;
  readonly character: string;
  readonly animations: Record<string, AtlasAnimationEntry>;
}

/* ──────────────────── Resolved runtime types ──────────────────── */

/** Resolved animation ready for rendering */
export interface SpriteAnimation {
  readonly name: string;
  readonly atlasUrl: string;
  readonly frameWidth: number;
  readonly frameHeight: number;
  readonly frameCount: number;
  readonly fps: number;
  readonly loop: boolean;
  readonly layout: 'strip' | 'grid';
  readonly totalRows: number;
  readonly currentRow: number;
}

/** Props for SpriteAnimator component */
export interface SpriteAnimatorProps {
  readonly entityType: string;
  readonly entityName: string;
  readonly animation: string;
  /** CSS pixel scale multiplier (default: 4) */
  readonly scale?: number;
  readonly playing?: boolean;
  readonly className?: string;
  readonly onComplete?: () => void;
  /** Current time-of-day condition for grid row selection */
  readonly condition?: string;
}

/** State of the sprite animation hook */
export interface SpriteAnimationState {
  readonly currentFrame: number;
  readonly isLoaded: boolean;
  readonly isPlaying: boolean;
  readonly error: string | null;
  readonly animation: SpriteAnimation | null;
}
