/**
 * Types for sprite animation system.
 * Maps to sprite-atlas.json v1.3 generated by asset-generator.
 */

/* ──────────────────── sprite-atlas.json schema ──────────────────── */

/** Condition for row selection in grid layouts */
export interface AtlasCondition {
  readonly type: string;   // e.g. "time_of_day"
  readonly value: string;  // e.g. "morning"
}

/** Row definition in a grid animation */
export interface AtlasRowDef {
  readonly rowIndex: number;
  readonly condition: AtlasCondition;
  readonly fps: number;
  readonly loop: boolean;
  /** Overlay-mode fields */
  readonly tint?: string;
  readonly opacity?: number;
}

/** Single animation entry in sprite-atlas.json */
export interface AtlasAnimationEntry {
  readonly file: string;
  readonly layout: 'strip' | 'grid';
  /** "sprite" (default) or "overlay" */
  readonly renderMode?: 'sprite' | 'overlay';
  readonly columns: number;
  readonly frameWidth: number;
  readonly frameHeight: number;
  // strip fields
  readonly fps?: number;
  readonly loop?: boolean;
  // grid fields
  readonly rows?: readonly AtlasRowDef[];
  readonly defaultRow?: number;
}

/** Root of sprite-atlas.json (v1.3 object format) */
export interface AtlasConfig {
  readonly configVersion: string;
  readonly revision: string;
  /** Entity name (was 'character' in v1.0) */
  readonly entity: string;
  /** Backward compat: old configs used 'character' */
  readonly character?: string;
  /**
   * Display scale multiplier applied by frontend.
   * Characters ~3.0, locations ~1.0. Default 1.0.
   */
  readonly displayScale?: number;
  readonly animations: Record<string, AtlasAnimationEntry>;
}

/* ──────────────────── Resolved runtime types ──────────────────── */

/** Resolved animation ready for rendering */
export interface SpriteAnimation {
  readonly name: string;
  readonly atlasUrl: string;
  readonly frameWidth: number;
  readonly frameHeight: number;
  readonly frameCount: number;
  readonly fps: number;
  readonly loop: boolean;
  readonly layout: 'strip' | 'grid';
  readonly renderMode: 'sprite' | 'overlay';
  readonly totalRows: number;
  readonly currentRow: number;
  /** Display scale from atlas config (default 1.0) */
  readonly displayScale: number;
  /** Overlay fields (only for renderMode === 'overlay') */
  readonly tint?: string;
  readonly opacity?: number;
}

/** Props for SpriteAnimator component */
export interface SpriteAnimatorProps {
  readonly entityType: string;
  readonly entityName: string;
  readonly animation: string;
  /**
   * Optional scale multiplier ON TOP of displayScale from atlas config.
   * Final CSS size = frameWidth * displayScale * scale.
   * Default: 1.0 (use displayScale as-is).
   */
  readonly scale?: number;
  readonly playing?: boolean;
  readonly className?: string;
  readonly onComplete?: () => void;
  /** Current time-of-day condition for grid row selection */
  readonly condition?: string;
}

/** State of the sprite animation hook */
export interface SpriteAnimationState {
  readonly currentFrame: number;
  readonly isLoaded: boolean;
  readonly isPlaying: boolean;
  readonly error: string | null;
  readonly animation: SpriteAnimation | null;
}
