/**
 * Types for sprite animation system.
 * Maps to atlas-config.json generated by asset-generator.
 */

/** Single animation entry from atlas-config.json */
export interface AtlasAnimationEntry {
  readonly name: string;
  readonly file?: string;
  readonly frameWidth: number;
  readonly frameHeight: number;
  readonly frames: number;
  readonly fps: number;
  readonly loop: boolean;
}

/** Combined atlas-config.json (array of entries) */
export type AtlasConfig = readonly AtlasAnimationEntry[];

/** Resolved animation ready for rendering */
export interface SpriteAnimation {
  readonly name: string;
  readonly atlasUrl: string;
  readonly frameWidth: number;
  readonly frameHeight: number;
  readonly frameCount: number;
  readonly fps: number;
  readonly loop: boolean;
}

/** Props for SpriteAnimator component */
export interface SpriteAnimatorProps {
  /** Entity type: 'characters', 'furniture', 'locations', 'ui' */
  readonly entityType: string;
  /** Entity name: 'tanya', 'bed', 'home_room', etc. */
  readonly entityName: string;
  /** Animation name to play: 'idle', 'walk', 'fire', etc. */
  readonly animation: string;
  /** CSS pixel scale multiplier (default: 4 for pixel-art upscale) */
  readonly scale?: number;
  /** Whether animation is currently playing (default: true) */
  readonly playing?: boolean;
  /** Optional CSS class name */
  readonly className?: string;
  /** Callback when animation completes one cycle (only for non-loop) */
  readonly onComplete?: () => void;
}

/** State of the sprite animation hook */
export interface SpriteAnimationState {
  readonly currentFrame: number;
  readonly isLoaded: boolean;
  readonly isPlaying: boolean;
  readonly error: string | null;
  readonly animation: SpriteAnimation | null;
}
