package com.sagat.life_of_t.domain.engine.parser;

import com.sagat.life_of_t.domain.engine.spec.VisualSpec;
import com.sagat.life_of_t.domain.engine.spec.VisualSpec.*;

import javax.xml.stream.XMLOutputFactory;
import javax.xml.stream.XMLStreamWriter;
import java.io.OutputStream;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * Writes a resolved (flat) VisualSpec back to XML.
 * Useful for debugging, cache generation, and the resolve CLI command.
 * Output contains no extends references — fully self-contained.
 */
public final class VisualSpecXmlWriter {

    private VisualSpecXmlWriter() {}

    public static void write(VisualSpec spec, OutputStream out) throws Exception {
        XMLStreamWriter w = XMLOutputFactory.newInstance()
                .createXMLStreamWriter(out, "UTF-8");

        w.writeStartDocument("UTF-8", "1.0");
        w.writeCharacters("\n");
        w.writeComment(" Resolved visual spec — generated by VisualSpecResolver. DO NOT EDIT. ");
        w.writeCharacters("\n");

        w.writeStartElement("asset-spec");
        w.writeAttribute("resolved", "true");
        w.writeCharacters("\n");

        writeMeta(w, spec);
        writePalette(w, spec);
        writeLayers(w, spec);
        writeAnimations(w, spec);

        w.writeEndElement();
        w.writeEndDocument();
        w.flush();
    }

    private static void writeMeta(XMLStreamWriter w, VisualSpec spec) throws Exception {
        w.writeCharacters("  ");
        w.writeStartElement("meta");
        w.writeCharacters("\n");
        writeSimpleElement(w, "entity-type", spec.entityType());
        writeSimpleElement(w, "entity-name", spec.entityName());
        writeSimpleElement(w, "spec-version", spec.specVersion());
        if (spec.canvas() != null) {
            w.writeCharacters("    ");
            w.writeEmptyElement("canvas");
            w.writeAttribute("width", String.valueOf(spec.canvas().width()));
            w.writeAttribute("height", String.valueOf(spec.canvas().height()));
            w.writeCharacters("\n");
        }
        writeSimpleElement(w, "display-scale",
                String.valueOf(spec.displayScale()));
        w.writeCharacters("  ");
        w.writeEndElement();
        w.writeCharacters("\n");
    }

    private static void writePalette(XMLStreamWriter w, VisualSpec spec) throws Exception {
        if (spec.colorPalette().isEmpty()) return;
        w.writeCharacters("  ");
        w.writeStartElement("color-palette");
        w.writeCharacters("\n");
        for (Map.Entry<String, String> entry : spec.colorPalette().entrySet()) {
            w.writeCharacters("    ");
            w.writeEmptyElement("color");
            w.writeAttribute("id", entry.getKey());
            w.writeAttribute("value", entry.getValue());
            w.writeCharacters("\n");
        }
        w.writeCharacters("  ");
        w.writeEndElement();
        w.writeCharacters("\n");
    }

    private static void writeLayers(XMLStreamWriter w, VisualSpec spec) throws Exception {
        w.writeCharacters("  ");
        w.writeStartElement("layers");
        w.writeCharacters("\n");
        for (LayerSpec layer : spec.layers()) {
            w.writeCharacters("    ");
            w.writeStartElement("layer");
            w.writeAttribute("id", layer.id());
            w.writeAttribute("type", layer.type());
            w.writeAttribute("z-order", String.valueOf(layer.zOrder()));
            w.writeAttribute("width", String.valueOf(layer.width()));
            w.writeAttribute("height", String.valueOf(layer.height()));
            w.writeCharacters("\n");

            w.writeCharacters("      ");
            w.writeStartElement("pixel-data");
            w.writeCharacters("\n");
            for (PixelPrimitive p : layer.pixelData()) {
                w.writeCharacters("        ");
                switch (p) {
                    case PixelRect r -> {
                        w.writeEmptyElement("rect");
                        w.writeAttribute("x", String.valueOf(r.x()));
                        w.writeAttribute("y", String.valueOf(r.y()));
                        w.writeAttribute("w", String.valueOf(r.w()));
                        w.writeAttribute("h", String.valueOf(r.h()));
                        w.writeAttribute("color",
                                r.resolvedColor(spec.colorPalette()));
                    }
                    case PixelLine l -> {
                        w.writeEmptyElement("hline");
                        w.writeAttribute("x", String.valueOf(l.x()));
                        w.writeAttribute("y", String.valueOf(l.y()));
                        w.writeAttribute("len", String.valueOf(l.len()));
                        w.writeAttribute("color",
                                l.resolvedColor(spec.colorPalette()));
                    }
                    case PixelDot d -> {
                        w.writeEmptyElement("pixel");
                        w.writeAttribute("x", String.valueOf(d.x()));
                        w.writeAttribute("y", String.valueOf(d.y()));
                        w.writeAttribute("color",
                                d.resolvedColor(spec.colorPalette()));
                    }
                }
                w.writeCharacters("\n");
            }
            w.writeCharacters("      ");
            w.writeEndElement();
            w.writeCharacters("\n");

            w.writeCharacters("    ");
            w.writeEndElement();
            w.writeCharacters("\n");
        }
        w.writeCharacters("  ");
        w.writeEndElement();
        w.writeCharacters("\n");
    }

    private static void writeAnimations(XMLStreamWriter w, VisualSpec spec) throws Exception {
        if (spec.animations().isEmpty()) return;
        w.writeCharacters("  ");
        w.writeStartElement("animations");
        w.writeCharacters("\n");
        for (AnimationSpec anim : spec.animations()) {
            w.writeCharacters("    ");
            w.writeStartElement("animation");
            w.writeAttribute("name", anim.name());
            w.writeAttribute("frames", String.valueOf(anim.frames()));
            w.writeAttribute("fps", String.valueOf(anim.fps()));
            w.writeAttribute("loop", String.valueOf(anim.loop()));
            w.writeAttribute("frame-width", String.valueOf(anim.frameWidth()));
            w.writeAttribute("frame-height", String.valueOf(anim.frameHeight()));
            w.writeCharacters("\n");
            for (FrameSpec frame : anim.frameSpecs()) {
                w.writeCharacters("      ");
                w.writeEmptyElement("frame");
                w.writeAttribute("index", String.valueOf(frame.index()));
                String offsets = frame.layerOffsets().entrySet().stream()
                        .map(e -> e.getKey() + ":" + e.getValue().dx()
                                + "," + e.getValue().dy())
                        .collect(Collectors.joining("; "));
                w.writeAttribute("layer-offsets", offsets);
                w.writeCharacters("\n");
            }
            w.writeCharacters("    ");
            w.writeEndElement();
            w.writeCharacters("\n");
        }
        w.writeCharacters("  ");
        w.writeEndElement();
        w.writeCharacters("\n");
    }

    private static void writeSimpleElement(
            XMLStreamWriter w, String name, String value) throws Exception {
        w.writeCharacters("    ");
        w.writeStartElement(name);
        w.writeCharacters(value);
        w.writeEndElement();
        w.writeCharacters("\n");
    }
}
