package ru.lifegame.assets.domain.model.asset;

import java.util.List;

/**
 * Schema definition for sprite-atlas.json — the versioned atlas configuration
 * generated by the asset pipeline and consumed by the frontend SpriteController.
 * <p>
 * <b>Config Version: 1.4</b>
 * <p>
 * Changes from 1.3:
 * <ul>
 *   <li>Added optional {@code cropOffset} to AnimationEntry — records the position
 *       of the content bounding box within the original canvas. When present, frames
 *       in the atlas are pre-cropped to their non-transparent pixels.
 *       Fields: x, y (offset from original top-left), originalWidth, originalHeight
 *       (the full uncropped canvas size). The entry's frameWidth/frameHeight reflect
 *       the cropped dimensions.</li>
 * </ul>
 * <p>
 * Changes from 1.2:
 * <ul>
 *   <li>Added {@code displayScale} — multiplier applied by the frontend when
 *       rendering sprites. Default: 1.0.</li>
 * </ul>
 * <p>
 * Changes from 1.1:
 * <ul>
 *   <li>Added {@code renderMode} to AnimationEntry: "sprite" (default) or "overlay".</li>
 *   <li>Added {@code tint} and {@code opacity} to RowDef for overlay animations.</li>
 *   <li>Renamed top-level {@code character} to {@code entity}.</li>
 * </ul>
 * <p>
 * Structure:
 * <pre>
 * {
 *   "configVersion": "1.4",
 *   "revision": "latest",
 *   "entity": "bookshelf",
 *   "displayScale": 1.0,
 *   "animations": {
 *     "idle": {
 *       "file": "idle_atlas.png",
 *       "layout": "strip",
 *       "renderMode": "sprite",
 *       "cropOffset": {
 *         "x": 40, "y": 100,
 *         "originalWidth": 256, "originalHeight": 192
 *       },
 *       "columns": 6,
 *       "frameWidth": 176,
 *       "frameHeight": 88,
 *       "fps": 2,
 *       "loop": true
 *     }
 *   }
 * }
 * </pre>
 */
public record AtlasConfigSchema(
        String configVersion,
        String revision,
        String entity,
        double displayScale,
        java.util.Map<String, AnimationEntry> animations
) {
    public static final String CURRENT_VERSION = "1.4";
    public static final String LATEST_REVISION = "latest";
    public static final double DEFAULT_DISPLAY_SCALE = 1.0;

    /**
     * Single animation entry within the config.
     *
     * @param file          atlas PNG filename (relative to animations/ dir)
     * @param layout        "grid" or "strip"
     * @param renderMode    "sprite" (default) or "overlay"
     * @param cropOffset    if frames were cropped, the offset within original canvas
     * @param columns       number of frame columns in the atlas
     * @param frameWidth    width of one animation frame in pixels (cropped if applicable)
     * @param frameHeight   height of one animation frame in pixels (cropped if applicable)
     * @param fps           playback fps (strip layout; grid rows override per-row)
     * @param loop          whether animation loops (strip; grid rows override)
     * @param rows          row definitions (only for grid layout)
     * @param defaultRow    default row index (only for grid layout)
     */
    public record AnimationEntry(
            String file,
            String layout,
            String renderMode,
            CropOffset cropOffset,
            int columns,
            int frameWidth,
            int frameHeight,
            int fps,
            boolean loop,
            List<RowDef> rows,
            int defaultRow
    ) {
        /** Strip constructor (always sprite mode, no crop) */
        public AnimationEntry(String file, int columns, int frameWidth, int frameHeight,
                              int fps, boolean loop) {
            this(file, "strip", "sprite", null, columns, frameWidth, frameHeight, fps, loop, List.of(), 0);
        }
    }

    /**
     * Crop offset info — present when animation frames were cropped to their
     * non-transparent bounding box during generation.
     *
     * @param x              X offset of cropped region from original canvas top-left
     * @param y              Y offset of cropped region from original canvas top-left
     * @param originalWidth  full uncropped canvas width
     * @param originalHeight full uncropped canvas height
     */
    public record CropOffset(
            int x,
            int y,
            int originalWidth,
            int originalHeight
    ) {}

    /**
     * Row definition for grid layouts.
     */
    public record RowDef(
            int rowIndex,
            Condition condition,
            String tint,
            Double opacity,
            int fps,
            boolean loop
    ) {
        public RowDef(int rowIndex, Condition condition, int fps, boolean loop) {
            this(rowIndex, condition, null, null, fps, loop);
        }
    }

    public record Condition(
            String type,
            String value
    ) {}
}
