package ru.lifegame.assets.domain.model.asset;

import java.util.List;

/**
 * Schema definition for sprite-atlas.json — the versioned atlas configuration
 * generated by the asset pipeline and consumed by the frontend SpriteController.
 * <p>
 * <b>Config Version: 1.1</b>
 * <p>
 * Changes from 1.0:
 * <ul>
 *   <li>Added {@code frameWidth} and {@code frameHeight} per animation entry
 *       (previously only global spriteWidth/spriteHeight existed, which was wrong
 *       because different animations can have different frame sizes)</li>
 *   <li>Global spriteWidth/spriteHeight kept for backward compat but deprecated</li>
 * </ul>
 * <p>
 * Structure:
 * <pre>
 * {
 *   "configVersion": "1.1",
 *   "revision": "latest",
 *   "character": "sam",
 *   "animations": {
 *     "idle": {
 *       "file": "idle_atlas.png",
 *       "layout": "grid",
 *       "columns": 4,
 *       "frameWidth": 96,
 *       "frameHeight": 80,
 *       "rows": [
 *         {
 *           "rowIndex": 0,
 *           "condition": { "type": "time_of_day", "value": "morning" },
 *           "fps": 4,
 *           "loop": true
 *         }
 *       ],
 *       "defaultRow": 0
 *     },
 *     "walk": {
 *       "file": "walk_atlas.png",
 *       "layout": "strip",
 *       "columns": 6,
 *       "frameWidth": 96,
 *       "frameHeight": 80,
 *       "fps": 8,
 *       "loop": true
 *     }
 *   }
 * }
 * </pre>
 * <p>
 * <b>Versioning strategy:</b>
 * <ul>
 *   <li>{@code configVersion} — schema version (semver). Frontend checks major: 1.* OK.</li>
 *   <li>{@code revision} — build revision. "latest" (default) = always use newest.
 *       Numbered revisions (e.g. "20260306-1") allow pinning for production.</li>
 * </ul>
 */
public record AtlasConfigSchema(
        String configVersion,
        String revision,
        String character,
        java.util.Map<String, AnimationEntry> animations
) {
    public static final String CURRENT_VERSION = "1.1";
    public static final String LATEST_REVISION = "latest";

    /**
     * Single animation entry within the config.
     *
     * @param file        atlas PNG filename (relative to animations/ dir)
     * @param layout      "grid" or "strip"
     * @param columns     number of frame columns in the atlas
     * @param frameWidth  width of one animation frame in pixels
     * @param frameHeight height of one animation frame in pixels
     * @param fps         playback fps (strip layout; grid rows override per-row)
     * @param loop        whether animation loops (strip; grid rows override)
     * @param rows        row definitions (only for grid layout)
     * @param defaultRow  default row index (only for grid layout)
     */
    public record AnimationEntry(
            String file,
            String layout,
            int columns,
            int frameWidth,
            int frameHeight,
            int fps,
            boolean loop,
            List<RowDef> rows,
            int defaultRow
    ) {
        /** Strip constructor */
        public AnimationEntry(String file, int columns, int frameWidth, int frameHeight,
                              int fps, boolean loop) {
            this(file, "strip", columns, frameWidth, frameHeight, fps, loop, List.of(), 0);
        }
    }

    /**
     * Row definition for grid layouts.
     */
    public record RowDef(
            int rowIndex,
            Condition condition,
            int fps,
            boolean loop
    ) {}

    /**
     * Condition for selecting a row.
     */
    public record Condition(
            String type,
            String value
    ) {}
}
