import type { LocationConfig } from '../types/location.types';

export type { LocationConfig };

const LOCATIONS: Record<string, LocationConfig> = {
  home_room: {
    id: 'home_room',
    name: 'Комната',
    locationAsset: 'home_room',
    backgroundAnimation: 'idle',
    furniture: [
      {
        id: 'bed',
        assetKey: 'bed',
        entityName: 'bed',
        x: 60,
        y: 120,
        width: 180,
        height: 120,
        sceneHeight: 25,
        scale: 1.0,
        zOrder: 2,
        actionCode: 'sleep',
        label: 'Кровать',
        animation: 'idle',
      },
      {
        id: 'desk',
        assetKey: 'desk',
        entityName: 'desk',
        x: 300,
        y: 140,
        width: 160,
        height: 100,
        sceneHeight: 20,
        scale: 1.0,
        zOrder: 2,
        actionCode: 'work_freelance',
        label: 'Рабочий стол',
        animation: 'idle',
      },
      {
        id: 'wardrobe',
        assetKey: 'wardrobe',
        entityName: 'wardrobe',
        x: 520,
        y: 100,
        width: 100,
        height: 160,
        sceneHeight: 30,
        scale: 1.0,
        zOrder: 2,
        actionCode: 'change_clothes',
        label: 'Шкаф',
        animation: 'idle',
      },
      {
        id: 'bookshelf',
        assetKey: 'bookshelf',
        entityName: 'bookshelf',
        x: 420,
        y: 100,
        width: 100,
        height: 140,
        sceneHeight: 28,
        scale: 1.0,
        zOrder: 2,
        actionCode: 'read_book',
        label: 'Книжная полка',
        animation: 'idle',
      },
      {
        id: 'yoga_mat',
        assetKey: 'yoga_mat',
        entityName: 'yoga_mat',
        x: 200,
        y: 280,
        width: 120,
        height: 60,
        sceneHeight: 12,
        scale: 1.0,
        zOrder: 1,
        actionCode: 'morning_yoga',
        label: 'Коврик для йоги',
        animation: 'idle',
      },
    ],
    characters: [
      {
        id: 'tanya',
        entityName: 'tanya',
        x: 240,
        y: 200,
        width: 80,
        height: 140,
        sceneHeight: 50,
        scale: 1.0,
        zOrder: 3,
        defaultAnimation: 'idle',
      },
    ],
  },

  kitchen: {
    id: 'kitchen',
    name: 'Кухня',
    locationAsset: 'kitchen',
    backgroundAnimation: 'idle',
    furniture: [
      {
        id: 'stove',
        assetKey: 'stove',
        entityName: 'stove',
        x: 80,
        y: 140,
        width: 140,
        height: 120,
        sceneHeight: 25,
        scale: 1.0,
        zOrder: 2,
        actionCode: 'cook_meal',
        label: 'Плита',
        animation: 'idle',
      },
      {
        id: 'fridge',
        assetKey: 'fridge',
        entityName: 'fridge',
        x: 260,
        y: 100,
        width: 100,
        height: 180,
        sceneHeight: 35,
        scale: 1.0,
        zOrder: 2,
        actionCode: 'eat_snack',
        label: 'Холодильник',
        animation: 'idle',
      },
      {
        id: 'kitchen_table',
        assetKey: 'kitchen_table',
        entityName: 'kitchen_table',
        x: 380,
        y: 200,
        width: 160,
        height: 100,
        sceneHeight: 20,
        scale: 1.0,
        zOrder: 2,
        actionCode: 'have_breakfast',
        label: 'Кухонный стол',
        animation: 'idle',
      },
      {
        id: 'coffee_maker',
        assetKey: 'coffee_maker',
        entityName: 'coffee_maker',
        x: 560,
        y: 150,
        width: 80,
        height: 80,
        sceneHeight: 15,
        scale: 1.0,
        zOrder: 2,
        actionCode: 'make_coffee',
        label: 'Кофемашина',
        animation: 'idle',
      },
    ],
    characters: [
      {
        id: 'tanya',
        entityName: 'tanya',
        x: 260,
        y: 200,
        width: 80,
        height: 140,
        sceneHeight: 50,
        scale: 1.0,
        zOrder: 3,
        defaultAnimation: 'idle',
      },
      {
        id: 'mom',
        entityName: 'mom',
        x: 420,
        y: 200,
        width: 80,
        height: 140,
        sceneHeight: 50,
        scale: 1.0,
        zOrder: 3,
        defaultAnimation: 'idle',
      },
    ],
  },

  dacha_yard: {
    id: 'dacha_yard',
    name: 'Дача',
    locationAsset: 'dacha_yard',
    backgroundAnimation: 'idle',
    furniture: [
      {
        id: 'garden_bed',
        assetKey: 'garden_bed',
        entityName: 'garden_bed',
        x: 80,
        y: 200,
        width: 160,
        height: 100,
        sceneHeight: 20,
        scale: 1.0,
        zOrder: 2,
        actionCode: 'garden_work',
        label: 'Грядки',
        animation: 'idle',
      },
      {
        id: 'bbq',
        assetKey: 'bbq',
        entityName: 'bbq',
        x: 300,
        y: 200,
        width: 100,
        height: 120,
        sceneHeight: 22,
        scale: 1.0,
        zOrder: 2,
        actionCode: 'bbq_with_family',
        label: 'Мангал',
        animation: 'idle',
      },
      {
        id: 'hammock',
        assetKey: 'hammock',
        entityName: 'hammock',
        x: 460,
        y: 180,
        width: 160,
        height: 80,
        sceneHeight: 15,
        scale: 1.0,
        zOrder: 2,
        actionCode: 'rest_in_hammock',
        label: 'Гамак',
        animation: 'idle',
      },
    ],
    characters: [
      {
        id: 'tanya',
        entityName: 'tanya',
        x: 260,
        y: 210,
        width: 80,
        height: 140,
        sceneHeight: 50,
        scale: 1.0,
        zOrder: 3,
        defaultAnimation: 'idle',
      },
      {
        id: 'dad',
        entityName: 'dad',
        x: 380,
        y: 210,
        width: 80,
        height: 140,
        sceneHeight: 50,
        scale: 1.0,
        zOrder: 3,
        defaultAnimation: 'idle',
      },
    ],
  },

  parents_cottage: {
    id: 'parents_cottage',
    name: 'Дом родителей',
    locationAsset: 'parents_cottage',
    backgroundAnimation: 'idle',
    furniture: [
      {
        id: 'sofa',
        assetKey: 'sofa',
        entityName: 'sofa',
        x: 100,
        y: 180,
        width: 180,
        height: 100,
        sceneHeight: 20,
        scale: 1.0,
        zOrder: 2,
        actionCode: 'watch_tv_with_parents',
        label: 'Диван',
        animation: 'idle',
      },
      {
        id: 'dining_table',
        assetKey: 'dining_table',
        entityName: 'dining_table',
        x: 340,
        y: 180,
        width: 180,
        height: 120,
        sceneHeight: 22,
        scale: 1.0,
        zOrder: 2,
        actionCode: 'family_dinner',
        label: 'Обеденный стол',
        animation: 'idle',
      },
    ],
    characters: [
      {
        id: 'tanya',
        entityName: 'tanya',
        x: 200,
        y: 200,
        width: 80,
        height: 140,
        sceneHeight: 50,
        scale: 1.0,
        zOrder: 3,
        defaultAnimation: 'idle',
      },
      {
        id: 'mom',
        entityName: 'mom',
        x: 340,
        y: 200,
        width: 80,
        height: 140,
        sceneHeight: 50,
        scale: 1.0,
        zOrder: 3,
        defaultAnimation: 'idle',
      },
      {
        id: 'dad',
        entityName: 'dad',
        x: 440,
        y: 200,
        width: 80,
        height: 140,
        sceneHeight: 50,
        scale: 1.0,
        zOrder: 3,
        defaultAnimation: 'idle',
      },
    ],
  },

  summer_camp: {
    id: 'summer_camp',
    name: 'Лагерь',
    locationAsset: 'summer_camp',
    backgroundAnimation: 'idle',
    furniture: [
      {
        id: 'campfire',
        assetKey: 'campfire',
        entityName: 'campfire',
        x: 260,
        y: 200,
        width: 120,
        height: 100,
        sceneHeight: 20,
        scale: 1.0,
        zOrder: 2,
        actionCode: 'campfire_stories',
        label: 'Костёр',
        animation: 'idle',
      },
      {
        id: 'tent',
        assetKey: 'tent',
        entityName: 'tent',
        x: 80,
        y: 160,
        width: 160,
        height: 120,
        sceneHeight: 25,
        scale: 1.0,
        zOrder: 2,
        actionCode: 'sleep_in_tent',
        label: 'Палатка',
        animation: 'idle',
      },
      {
        id: 'sports_field',
        assetKey: 'sports_field',
        entityName: 'sports_field',
        x: 440,
        y: 200,
        width: 160,
        height: 100,
        sceneHeight: 20,
        scale: 1.0,
        zOrder: 1,
        actionCode: 'sports_day',
        label: 'Спортплощадка',
        animation: 'idle',
      },
    ],
    characters: [
      {
        id: 'tanya',
        entityName: 'tanya',
        x: 260,
        y: 200,
        width: 80,
        height: 140,
        sceneHeight: 50,
        scale: 1.0,
        zOrder: 3,
        defaultAnimation: 'idle',
      },
    ],
  },

  office: {
    id: 'office',
    name: 'Офис',
    locationAsset: 'office',
    backgroundAnimation: 'idle',
    furniture: [
      {
        id: 'work_desk',
        assetKey: 'work_desk',
        entityName: 'work_desk',
        x: 100,
        y: 160,
        width: 180,
        height: 100,
        sceneHeight: 20,
        scale: 1.0,
        zOrder: 2,
        actionCode: 'work_office',
        label: 'Рабочее место',
        animation: 'idle',
      },
      {
        id: 'meeting_table',
        assetKey: 'meeting_table',
        entityName: 'meeting_table',
        x: 340,
        y: 180,
        width: 200,
        height: 120,
        sceneHeight: 22,
        scale: 1.0,
        zOrder: 2,
        actionCode: 'team_meeting',
        label: 'Переговорная',
        animation: 'idle',
      },
      {
        id: 'coffee_point',
        assetKey: 'coffee_point',
        entityName: 'coffee_point',
        x: 560,
        y: 160,
        width: 80,
        height: 100,
        sceneHeight: 20,
        scale: 1.0,
        zOrder: 2,
        actionCode: 'office_coffee',
        label: 'Кофе-поинт',
        animation: 'idle',
      },
    ],
    characters: [
      {
        id: 'tanya',
        entityName: 'tanya',
        x: 200,
        y: 200,
        width: 80,
        height: 140,
        sceneHeight: 50,
        scale: 1.0,
        zOrder: 3,
        defaultAnimation: 'idle',
      },
      {
        id: 'colleague',
        entityName: 'colleague',
        x: 380,
        y: 200,
        width: 80,
        height: 140,
        sceneHeight: 50,
        scale: 1.0,
        zOrder: 3,
        defaultAnimation: 'idle',
      },
    ],
  },

  park: {
    id: 'park',
    name: 'Парк',
    locationAsset: 'park',
    backgroundAnimation: 'idle',
    furniture: [
      {
        id: 'park_bench',
        assetKey: 'park_bench',
        entityName: 'park_bench',
        x: 120,
        y: 200,
        width: 140,
        height: 80,
        sceneHeight: 15,
        scale: 1.0,
        zOrder: 2,
        actionCode: 'sit_in_park',
        label: 'Скамейка',
        animation: 'idle',
      },
      {
        id: 'jogging_path',
        assetKey: 'jogging_path',
        entityName: 'jogging_path',
        x: 300,
        y: 240,
        width: 200,
        height: 60,
        sceneHeight: 12,
        scale: 1.0,
        zOrder: 1,
        actionCode: 'go_jogging',
        label: 'Беговая дорожка',
        animation: 'idle',
      },
      {
        id: 'ice_cream_stand',
        assetKey: 'ice_cream_stand',
        entityName: 'ice_cream_stand',
        x: 520,
        y: 160,
        width: 100,
        height: 120,
        sceneHeight: 22,
        scale: 1.0,
        zOrder: 2,
        actionCode: 'buy_ice_cream',
        label: 'Мороженое',
        animation: 'idle',
      },
    ],
    characters: [
      {
        id: 'tanya',
        entityName: 'tanya',
        x: 260,
        y: 200,
        width: 80,
        height: 140,
        sceneHeight: 50,
        scale: 1.0,
        zOrder: 3,
        defaultAnimation: 'idle',
      },
    ],
  },
};

export function getLocationConfig(locationId: string): LocationConfig {
  return LOCATIONS[locationId] ?? LOCATIONS['home_room']!;
}

export function getLocationForTimeSlot(timeSlot: string): string {
  switch (timeSlot) {
    case 'MORNING': return 'home_room';
    case 'DAY':     return 'office';
    case 'EVENING': return 'home_room';
    case 'NIGHT':   return 'home_room';
    default:        return 'home_room';
  }
}
