package ru.lifegame.backend.api.controller;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.io.ClassPathResource;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Path;

/**
 * REST API for serving sprite-atlas.json configs generated by asset-generator module.
 * Frontend loads these configs to know animation layout, fps, conditions, etc.
 * 
 * Generated assets are in classpath:assets/ (copied from target/generated-assets/ during build).
 */
@RestController
@RequestMapping("/api/v1/assets")
public class AssetConfigController {

    private static final Logger log = LoggerFactory.getLogger(AssetConfigController.class);
    private final ObjectMapper objectMapper;

    public AssetConfigController(ObjectMapper objectMapper) {
        this.objectMapper = objectMapper;
    }

    /**
     * Get sprite-atlas.json for a specific asset.
     * 
     * @param type Asset type: characters, locations, furniture, ui, system, abstract
     * @param id   Entity ID: sam, kitchen, bed, etc.
     * @return JSON config with animations, frames, fps, conditions
     * 
     * Example: GET /api/v1/assets/configs/characters/sam
     *   Returns: assets/characters/sam/sprite-atlas.json
     */
    @GetMapping("/configs/{type}/{id}")
    public ResponseEntity<JsonNode> getAtlasConfig(
            @PathVariable String type,
            @PathVariable String id
    ) {
        try {
            // Build path to sprite-atlas.json
            String resourcePath = String.format("assets/%s/%s/sprite-atlas.json", type, id);
            ClassPathResource resource = new ClassPathResource(resourcePath);
            
            if (!resource.exists()) {
                log.warn("Atlas config not found: {}", resourcePath);
                return ResponseEntity.notFound().build();
            }
            
            // Read and parse JSON
            try (InputStream is = resource.getInputStream()) {
                JsonNode config = objectMapper.readTree(is);
                log.debug("Serving atlas config: {} (rev: {})", 
                    resourcePath, 
                    config.path("revision").asText("unknown"));
                return ResponseEntity.ok(config);
            }
            
        } catch (IOException e) {
            log.error("Failed to load atlas config for {}/{}: {}", type, id, e.getMessage());
            return ResponseEntity.internalServerError().build();
        }
    }
}
